# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeAuto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
 pod 'OpenSSL-Universal'

  # Pods for HomeAuto

  target 'HomeAutoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HomeAutoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
